// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "dDriveMecanum.h"
dDriveMecanum::dDriveMecanum() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void dDriveMecanum::Initialize() {
	count = 0;
}
// Called repeatedly when this Command is scheduled to run
void dDriveMecanum::Execute() {
	Joystick* js = Robot::oi->getxBox();
	float x = js->GetX();
	float y = js->GetY();
	
	if(x > .15)
		x -= .15;
	else if(x < -.15)
		x += .15;
	else
		x = 0;
	
	if(y > .15)
		y -= .15;
	else if(y < -.15)
		y += .15;
	else
		y = 0;
	
	x *= (20/17);
	y *= (20/17);
	
	Robot::driveTrain->MecanumDrive(x, y, js->GetZ()*-1);
	
	count++;
}
// Make this return true when this Command no longer needs to run execute()
bool dDriveMecanum::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void dDriveMecanum::End() {
	Robot::driveTrain->SetSpeed(0, 0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void dDriveMecanum::Interrupted() {
	Robot::driveTrain->SetSpeed(0, 0);
}
