// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "fPreset4.h"
fPreset4::fPreset4() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void fPreset4::Initialize() {
	Robot::shooter1->PresetInit();
}
// Called repeatedly when this Command is scheduled to run
void fPreset4::Execute() {
	Robot::shooter1->PresetExecute(0, 0);
}
// Make this return true when this Command no longer needs to run execute()
bool fPreset4::IsFinished() {
	return Robot::shooter1->PresetIsFinished();
}
// Called once after isFinished returns true
void fPreset4::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void fPreset4::Interrupted() {
}
