// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "fShooterNoPID.h"
fShooterNoPID::fShooterNoPID() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void fShooterNoPID::Initialize() {
	count = 0;
}
// Called repeatedly when this Command is scheduled to run
void fShooterNoPID::Execute() {
	Robot::shooter->SetSpeed(.8);
	
	if(count%10 == 0)
		printf("RPM: %f\n", Robot::shooter->GetRPM());
	
	count++;
}
// Make this return true when this Command no longer needs to run execute()
bool fShooterNoPID::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void fShooterNoPID::End() {
	Robot::shooter->SetSpeed(0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void fShooterNoPID::Interrupted() {
	Robot::shooter->SetSpeed(0);
}
