// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "fShoot.h"
fShoot::fShoot() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void fShoot::Initialize() {
	count = 0;
	pressed = false;
	done = false;
	Robot::shooter->loader->Set(-1, 0);
}
// Called repeatedly when this Command is scheduled to run
void fShoot::Execute() {
	if(count > 100 && pressed)
	{
		printf("SHOOTER DONE\n");
		done = true;
	}
	
	if(Robot::shooter->shooterLimit->Get() == 1 && count > 30 && count < 10000)
	{
		printf("Shooter Don=================\n");
		Robot::shooter->loader->Set(0, 0);
		count = 0;
		pressed = true;
	}
	
	count++;
}
// Make this return true when this Command no longer needs to run execute()
bool fShoot::IsFinished() {
	return done;
}
// Called once after isFinished returns true
void fShoot::End() {
	Robot::shooter->loader->Set(0, 0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void fShoot::Interrupted() {
	Robot::shooter->loader->Set(0, 0);
}
