// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "nFan.h"
nFan::nFan() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::net);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void nFan::Initialize() {
	count = 0;
}
// Called repeatedly when this Command is scheduled to run
void nFan::Execute() {
	if(Robot::net->fanOn)
		Robot::net->fan->Set(1, 0);
	else
		Robot::net->fan->Set(0, 0);
	
	if(count%50 == 0)
		printf("Fan on: %i", Robot::net->fanOn);
	
	count++;
}
// Make this return true when this Command no longer needs to run execute()
bool nFan::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void nFan::End() {
	Robot::net->fan->Set(0, 0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void nFan::Interrupted() {
	Robot::net->fan->Set(0, 0);
}
