// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef CAMERA_H
#define CAMERA_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Camera: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	struct Scores {
				double rectangularity;
				double aspectRatioInner;
				double aspectRatioOuter;
				double xEdge;
				double yEdge;
				float xCtr;
				float yCtr;
				
				};
	
	Camera();
	void InitDefaultCommand();
	
	AxisCamera &m_camera;
	ColorImage image;
	Task m_targeting;
	bool m_prevCapture;
	Scores *m_scores;
	float targetx;
	float targety;
	
	float GetTargetx();
	float GetTargety();
	
	void TargetingTask();
};
#endif
